version: '3.4'

services:
  dockerservicedemo:
    image: ${DOCKER_REGISTRY}backend
    build:
      context: .
      dockerfile: backend
    ports:
      - 5000:8080
  proxy:
    image: nginx:latest
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5001:80