version: '3.4'

services:
  backend:
    container_name: backend
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - 8080:8080
      - 8081:8081
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - 3000:3000
